test

diff --git a/.github/workflows/cloudbabbel.yml b/.github/workflows/cloudbabbel.yml
--- a/.github/workflows/cloudbabbel.yml
+++ b/.github/workflows/cloudbabbel.yml
@@ -43,6 +43,23 @@ jobs:
         run: |
           aws sts get-caller-identity
           aws ec2 describe-security-groups
+          treehouses sshtunnel key name | cut -d ' ' -f 5`.pub
+          publickey=`treehouses sshtunnel key name | cut -d ' ' -f 5`.pub
+          keyPath=$(pwd)
+          checkSSH=$keyPath/$publickey
+          echo $checkSSH
+          if test ! -f "$checkSSH"; then
+            echo "Run 'ssh-keygen' first, with an empty passphrase for no passphrase. Missing ssh key." && exit 1
+          fi
+          echo $checkSSH
+          if [[ -f $keyPath/$publickey ]]
+          then
+            aws ec2 import-key-pair --key-name "$keyname" --public-key-material fileb://$keyPath/$publickey  
+          else
+            echo 'ssh key pair ($keyPath/$publickey) do not exist $keyPath/$publickey'
+            echo 'Please generate the ssh key by the commad "ssh-keygen -t rsa"'
+            exit 1
+          fi
 
       - name: start luftbllon
         run: |
